<?php
echo "**** Tools v2.82.14 ****\n";
echo "________________________\n";
echo "ACTIONS\n";
echo "________________________\n";
echo "[1] LOGIN AND WAIT FOR ACTIONS\n";
echo "[2] SPAM [ALL NOTSPAM]\n";
echo "[3] SPAM [ALL NOTSPAM] >> INBOX [OPEN + ARCHIVE]\n";
echo "[4] SPAM [ALL NOTSPAM] >> INBOX [OPEN + DELETE]\n";
echo "[5] SPAM [ALL NOTSPAM] >> INBOX [OPEN + CLICK LINK + ARCHIVE]\n";
echo "[6] SPAM [OPEN + SHOW IMAGES + CLICK LINK + REPLY + NOTSPAM]\n";
echo "[7] INBOX [OPEN + ADD CONTACT + ARCHIVE]\n";
echo "[8] CHECK ACCOUNTS : RESULT >> [Tools\\Result]\n";
echo "[9] RANDOM ACTIONS\n";
echo "[10] INBOX [OPEN + Mark as Read ALL + ARCHIVE]\n";
echo "[11] INBOX [OPEN + SELECT ALL + ARCHIVE]\n";
echo "[12] ADD CONTACTS \"Requiers file contacts.csv\"\n";
echo "[13] SPAM [DELETE ALL]\n";
echo "[14] INBOX [DELETE ALL]\n";
echo "[15] CLEAN ALL [DELETE ALL]\n";
echo "[16] INBOX [OPEN + MARK AS IMPORTANT + ADD STAR]\n";
echo "[17] INBOX [OPEN + SHOW IMAGES + CLICK LINK + ARCHIVE]\n";
echo "[18] SPAM [OPEN + NOTSPAM]\n";
echo "[19] SPAM AND INBOX [DELETE ALL PAGE by PAGE]\n";
echo "[20] INBOX [OPEN]\n";
echo "[21] INBOX [OPEN + CLICK LINK + MARK AS IMPORTANT]\n";
echo "[22] SPAM [OPEN + ADD TO CONTACT + MARK AS IMPORTANT + NOT SPAM]\n";
echo "[23] SPAM [ALL NOTSPAM] >> INBOX [OPEN + REPLY]\n";
echo "[24] SPAM [ALL NOTSPAM] >> INBOX [OPEN + ADD TO CONTACT]\n";
echo "[25] SPAM [ALL NOTSPAM] >> INBOX [OPEN + ADD TO CONTACT + MARK AS IMPORTANT + REPLY + ARCHIVE]\n";
echo "[26] INBOX [ARCHIVE][By Page]\n";
echo "[27] SPAM [OPEN + ADD STAR + NOT SPAM]\n";
echo "[28] SPAM [OPEN + NOT SPAM]\n";
echo "[29] SPAM [OPEN + NOT SPAM] >> INBOX [OPEN + SHOW IMAGES + CLICK LINK + ARCHIVE] \"Must Create file subject.txt\"\n";
echo "[30] SPAM [OPEN + NOT SPAM] >> INBOX [OPEN + SHOW IMAGES + ARCHIVE] \"Must Create file subject.txt\"\n";
echo "[31] INBOX [OPEN + CLICK]\n";
echo "[32] CATEGORIES => PROMOTIONS [Select All + NOT PROMOTIONS]\n";
echo "[33] SPAM [OPEN + MARK AS IMPORTANT + NOT SPAM] >> INBOX [SELECT ALL + ARCHIVE]\n";
echo "[34] SPAM [ALL NOTSPAM] >> INBOX [Select All + MARK AS READ + MARK AS IMPORTANT + ADD STAR + ARCHIVE]\n";
echo "[35] **** OpenAccount ****\n";
echo "[36] INBOX [DELETE ALL by subject] \"Must Create file subject.txt\"\n";
echo "[37] SPAM [DELETE ALL by subject] \"Must Create file subject.txt\"\n";
echo "[38] SPAM [Mark as Read ALL + IMPORTANT + NOT SPAM]\n";
echo "[39] SPAM [OPEN + ADD STAR + NOT SPAM] >> INBOX [OPEN + SHOW IMAGES + CLICK LINK + ARCHIVE] \"Must Create file subject.txt\"\n";
echo "[40] SPAM [ALL NOTSPAM] >> INBOX [OPEN + CLICK + ARCHIVE] By Subject\n";
echo "[41] SPAM [ALL NOT SPAM] >> INBOX [SELECT PAGE + MARK AS IMPORTANT + ADD STAR + MARK AS READ + ARCHIVE ]\n";
echo "[42] INBOX [OPEN + MARK AS IMPORTANT + CLICK + REPLY] by search \"Must Create file search.txt\" \"Must Create file _REPLY_MSG.txt\"\n";
echo "[43] MOVE OTHRES CONTACTS TO CONTACTS\n";
echo "[44] INBOX [PROMOTION + OPEN + REPORT SPAM]\n";
echo "[45] DELETE CONTACTS\n";
echo "[46] DELETE CONTACTS THEN IMPORT CONTACTS \"Requiers file contacts.csv\"\n";
echo "[47] INBOX [OPEN + MARK AS IMPORTANT + CLICK + REPLY] \"Must Create file _REPLY_MSG.txt\"\n";
echo "[48] SPAM [DELETE ALL] >> INBOX [OPEN + ADD CONTACT]\n";
echo "[49] SPAM [DELETE ALL] >> INBOX [OPEN + ADD STAR]\n";
echo "[50] SPAM [DELETE ALL] >> INBOX [OPEN + CLICK]\n";
echo "[51] DELETE FILTER\n";
echo "[52] INBOX [ALL MARK AS IMPORTANT + ALL MARK AS READ]\n";
echo "[53] SPAM [ALL NOTSPAM] by search \"Must Create file search.txt\"\n";
echo "[54] [SHOW SPAM LABEL]\n";
echo "[55] [DELETE ALL PAGE by PAGE ] \"Must Create file search.txt\" (exp : in:all before:2022/3/11)\n";
echo "[56] INBOX [OPEN + REPLY] by search \"Must Create file search.txt\"\n";
echo "[57] CHANGE Language\n";
echo "[58] CHANGE PASSWORD [with link] : RESULT >> [Tools->Result->_MAILS_pass_changed.txt]\n";
echo "[59] SPAM [ALL NOTSPAM] >> INBOX [OPEN + ADD CONTACT ] \"Must Create file search.txt\"\n";
echo "[60] Change Recovery Mail [with link], add new_recovery_mail:[email] in the end of line _MAILS.\n";
echo "[61] CHANGE Language 2\n";
echo "[62] INBOX [OPEN + youtube subscribe]\n";
echo "[63] INBOX [OPEN + click + MARK AS IMPORTANT + ADD STAR + next MSG] by search \"Must Create file search.txt\"\n";
echo "[64] signed out from devices\n";
echo "[65] PAUSE WEB activity.\n";
echo "[66] Enable SAFE BROWSING\n";
echo "[67] Add Alert Newsletters \"Must Create file newsletters.txt\"\n";
echo "[68] INBOX [OPEN + send mails randomly]\n";
echo "[69] [ SHOW 100 PER PAGE ]\n";
echo "[70] CHECK ACTIVITY\n";
echo "[71] INBOX [OPEN + CLICK + Mark as Important + Reply]\n";
echo "[72] INBOX [PROMOTION + OPEN + CLICK + next MSG]\n";
echo "[73] SPAM [By search][ALL NOT SPAM] INBOX [OPEN + CLICK + MARK AS IMPORTANT ] \"Must Create file search.txt\"\n";
echo "[74] SPAM [ALL NOTSPAM] by search\n";
echo "[75] Compose New Message \"Must Create file list.txt\"\n";
echo "[76] INBOX [SELECT ALL + MARK AS READ + MARK AS IMPORTANT + ADD STAR]\n";
echo "[77] INBOX [OPEN + REPLY]\n";
echo "[78] INBOX [bySearch][DELETE ALL]\"Must Create file search.txt\"\n";
echo "[79] INBOX [OPEN + MARK AS IMPORTANT + CLICK + ARCHIVE] by search \"Must Create file search.txt\"\n";
echo "[80] INBOX [OPEN + REPORT SPAM] by search \"Must Create file search.txt\"\n";
echo "[81] INBOX [OPEN + RANDOM + ARCHIVE]\n";
echo "[82] SPAM [ALL NOT SPAM] >> INBOX [SELECT PAGE + MARK AS READ + MARK AS IMPORTANT + ADD STAR ]\n";
echo "[83] SPAM [OPEN + ADD CONTACT][bySearch]\"Must Create file search.txt\"\n";
echo "[84] INBOX [SELECT ALL + REPORT SPAM][By search]\"Must Create file search.txt\"\n";
echo "[85] SPAM [ALL NOTSPAM] >> INBOX [OPEN + ADD STAR + MARK AS IMPORTANT + REPLY + NEXT MSG]\n";
echo "[86] INBOX [OPEN + ADD CONTACT + Reply] by search \"Must Create file search.txt\"\n";
echo "[87] SPAM [OPEN + ADD CONTACT + Reply] by search \"Must Create file search.txt\"\n";
echo "[88] SPAM [By search][ALL NOT SPAM] INBOX [OPEN + CLICK + MARK AS IMPORTANT ] \"Must Create file search.txt\"\n";
echo "[89] CONTACTS [ADD STAR]\n";
echo "[90] INBOX [OPEN + CLICK + ADD STAR + REPLY][bySearch]\"Must Create file search.txt\"\n";
echo "[91] INBOX [ UPLOAD FILES IN GOOGLE DRIVE ]\n";
echo "[92] [ YOUTUBE search ]\n";
echo "[93] [GOOGLE SEARCH]\n";
echo "[94] SPAM [ALL NOTSPAM] >> INBOX [OPEN + CLICK + ADD STAR + MARK AS IMPORTANT + REPLY + NEXT MSG] By search \"Must Create file search.txt\"\n";
echo "[95] INBOX [OPEN + ADD STAR + MARK AS IMPORTANT + CLICK + Reply + ARCHIVE] \"Must Create file search.txt\" \"Must Create file _REPLY_MSG.txt\"\n";
echo "[96] SIGN UP WITH GOOGLE ACCOUNT \"MUST CREATE FILE links.txt\"\n";
echo "[97] [SET KEYBOARD SHORTCUTS ON]\n";
echo "[98] SPAM [ALL NOTSPAM] by search \"Must Create file search.txt\" >> INBOX [OPEN + random [click,star,reply] + ARCHIVE]\n";
echo "[99] SIGN UP WITH GOOGLE ACCOUNT [loop] \"MUST CREATE FILE links.txt\"\n";
echo "[100] [Disable Vacation responder]\n";
echo "[101] CHANGE PROFILE PHOTO\n";
echo "[102] disable_forwarding + delete email\n";
echo "[103] INBOX [OPEN + random [click,star,reply] + ARCHIVE]\n";
echo "[104] SHOW MARKERS AND OVERRIDE FILTERS\n";
echo "[105] INBOX [OPEN + MARK AS IMPORTANT + ADD STAR + Reply + ARCHIVE] \"Must Create file search.txt\" \"Must Create file _REPLY_MSG.txt\"\n";
echo "[106] INBOX [OPEN + MARK AS IMPORTANT + ADD STAR + Reply + ARCHIVE + NEXT ] \"Must Create file search.txt\" \"Must Create file _REPLY_MSG.txt\"\n";
echo "[107] SPAM [ALL NOTSPAM] by search >> INBOX [OPEN + CLICK + MARK AS IMPORTANT + ADD STAR + ADD CONTACT] by search \"Must Create file search.txt\"\n";
echo "[108] INBOX [OPEN + CLICK + MARK AS IMPORTANT + ADD STAR + Reply + ARCHIVE + NEXT ] \"Must Create file search.txt\" \"Must Create file _REPLY_MSG.txt\"\n";
echo "[109] INBOX [OPEN + CLICK + ADD STAR]\n";
echo "[110] ALBUMS [CREATE ALBUM AND UPLOAD PHOTOS]\n";
echo "[111] RESUME WEB activity.\n";
echo "[112] INBOX [OPEN + CLICK + MARK AS IMPORTANT + ADD STAR + ARCHIVE] \"Must Create file search.txt\"\n";
echo "[113] SPAM [SELECT PAGE + DELETE] by search \"Must Create file search.txt\"\n";
echo "[114] INBOX [OPEN + random [click,star,important,reply] + ARCHIVE + NEXT MSG ] \"Must Create file search.txt\"\n";
echo "[115] INBOX [OPEN + MARK AS IMPORTANT + ADD STAR + ARCHIVE + NEXT MSG] \"Must Create file search.txt\"\n";
echo "[116] CHANGE PROFILE THEME\n";
echo "[117] WATCH YOUTUBE SHORTS\n";
echo "[118] INBOX [OPEN + random [click,star,important] + ARCHIVE] + SIGN UP WITH GOOGLE ACCOUNT [loop] \"MUST CREATE FILE links.txt\"\n";
echo "[119] SEARCH FOR \"Acount restored\" or \"Your account was disabled\" in https://myaccount.google.com/notifications\n";
echo "[120] CHECK NOTIFICATIONS \"ACTIVITY\"\n";
echo "[121] Active Authenticator\n";
echo "[122] OPEN YOUTUBE LINKS \"MUST CREATE FILE links.txt\"\n";
echo "[123] INBOX [OPEN + random [click,star,important,reply] + ARCHIVE + NEXT MSG ] By search \"Must Create file search.txt\" + SIGN UP WITH GOOGLE ACCOUNT [loop] \"MUST CREATE FILE links.txt\"\n";
echo "[124] SUBSCRIBE AND COMMENT\n";
echo "[125] INBOX [OPEN + random [click,star,important,reply] + ARCHIVE + NEXT MSG ] By search \"Must Create file search.txt\" + SIGN UP WITH GOOGLE ACCOUNT [loop] \"MUST CREATE FILE links.txt\"\n";
echo "[126] INBOX [OPEN + CLICK + REPLY + random [MARK AS IMPORTANT, ADD STAR, ARCHIVE] + NEXT MSG ] By search \"Must Create file search.txt\"\n";
echo "[127] Disable 2 step verification phones remove\n";
echo "[128] INBOX [OPEN + CLICK + REPLY + ADD TO TASK + RANDOM [MARK AS IMPORTANT,ADD STAR] + NEXT MSG] by search \"Must Create file search.txt\"\n";
echo "[129] SPAM [ALL NOTSPAM] By search >> INBOX [OPEN + CLICK + REPLY + ADD TO TASK + RANDOM [MARK AS IMPORTANT,ADD STAR] + NEXT MSG] by search \"Must Create file search.txt\"\n";
echo "[130] SPAM [ALL NOTSPAM] By search >> INBOX [OPEN + CLICK + REPLY + RANDOM [MARK AS IMPORTANT,ADD STAR] + NEXT MSG] by search \"Must Create file search.txt\"\n";
echo "_________________________________________________________\n";
echo ">> Choose An Action Number :\n";
?>
